= arconia image build dockerfile

The `image build dockerfile` command builds a container image for your Spring Boot application using a Dockerfile.

== Usage

Basic usage:

[source,shell]
----
arconia image build dockerfile --image-name ghcr.io/thomasvitale/my-app:4.2.0
----

With custom Dockerfile path:

[source,shell]
----
arconia image build dockerfile --image-name ghcr.io/thomasvitale/my-app:4.2.0 --dockerfile config/Dockerfile
----

== Options

The following options are available:

[cols="1,1,3"]
|===
|Option |Default |Description

|`--image-name` or `-t`
|
|Name for the image to build.

|`--dockerfile` or `-f`
|
a|The path to the Dockerfile to use for building the container image. If not specified, the command will look for a Dockerfile in the following locations:

* `src/main/docker/Dockerfile`
* `Dockerfile` (in project root)

|`--debug` or `-d`
|`false`
|Include debug output.

|`--verbose` or `-v`
|`false`
|Include more verbose output about the execution.

|`--stacktrace` or `-s`
|`false`
|Include more details about errors.

|`--help` or `-h`
|
|Display help information for the command.
|===

== See Also

* xref:image/buildpacks.adoc[arconia image build buildpacks]
* https://docs.docker.com/engine/reference/commandline/build/[Docker build reference]
