version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
