spring:
  application:
    name: arconia-cli
  main:
    banner-mode: off
    web-application-type: none
  shell:
    command:
      history:
        enabled: false
      script:
        enabled: false
    option:
       naming:
         case-type: kebab

logging:
  pattern:
    console:
