= `arconia dev`

The `arconia dev` command runs your Spring Boot application in development mode. It delegates to your build tool's (Maven/Gradle) development tasks to start the application with optimized settings for local development provided by the https://arconia.io/docs/arconia/latest/index.html[Arconia Framework].

== Usage

Basic usage:

[source,shell]
----
arconia dev
----

== Options

The following options are available:

[cols="1,1,3"]
|===
|Option |Default |Description

|`--test` or `-t`
|`false`
|Run the application from the test classpath.

|`--debug` or `-d`
|`false`
|Include debug output.

|`--verbose` or `-v`
|`false`
|Include more verbose output about the execution.

|`--stacktrace` or `-s`
|`false`
|Include more details about errors.

|`--params` or `-p`
|
|Additional build parameters passed directly to the build tool.

|`--help` or `-h`
|
|Display help information for the command.
|===

== Build Tool Integration

The `dev` command automatically detects whether your project uses Maven or Gradle and runs the appropriate development task:

[cols="1,3"]
|===
|Build Tool |Command

|Gradle
a|

* `./gradlew bootRun` (Linux/macOS with wrapper)
* `gradle bootRun` (Linux/macOS without wrapper)
* `gradlew.bat bootRun` (Windows with wrapper)
* `gradle bootRun` (Windows without wrapper)

|Maven
a|One of:

* `./mvnw spring-boot:run` (Linux/macOS with wrapper)
* `mvn spring-boot:run` (Linux/macOS without wrapper)
* `mvnw.cmd spring-boot:run` (Windows with wrapper)
* `mvn spring-boot:run` (Windows without wrapper)
* `mvnd spring-boot:run` (Using Maven Daemon)
|===

Any additional parameters specified with `--params` are passed through to the respective build tool command.

If you want to run the application from the test classpath, you can use the `--test` option. This will run the application using the test classpath instead of the main classpath, which is useful when using the low-level Testcontainers support in Spring Boot at development time. In that case, the command will be `gradle bootTestRun` for Gradle and `mvn spring-boot:test-run` for Maven.

== Workflow

To get get the best out of this workflow, you can rely on Arconia for getting an enhanced developer experience on top of Spring Boot, including Arconia Dev Services and integration with the Spring Boot DevTools. For example:

[source,groovy]
----
dependencies {
  implementation "io.arconia:arconia-spring-boot-starter"
  developmentOnly "org.springframework.boot:spring-boot-devtools"
  testAndDevelopmentOnly "io.arconia:arconia-dev-services-postgresql"
}

dependencyManagement {
	imports {
		mavenBom "io.arconia:arconia-bom:0.14.0"
	}
}
----

== See Also

* xref:development/build.adoc[arconia build]
* xref:development/test.adoc[arconia test]
