version = 1

[install]
graalvm-ce.pkg-path = "graalvm-ce"
graalvm-ce.version = "24.0.1"
vscode-java-flake.flake = "github:thomasvitale/vscode-java-flake"

[vars]
FLOX_DISABLE_METRICS="true"

[profile]
common = '''
  export JAVA_HOME=$FLOX_ENV
'''

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
