name: Commit Stage

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.sdkmanrc'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.sdkmanrc'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Check out source code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
      
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@22cc13fe88ef133134b3798e128fb208df55e1f5 # v1.2.3
        with:
          java-version: '23'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      
      - name: Set VERSION environment variable
        id: set_version
        run: |
          VERSION=$(./gradlew properties | grep 'version:' | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Compile and test
        run: ./gradlew build
      
      - name: Native compile and test
        run: ./gradlew nativeBuild

  assemble:
    name: Assemble
    needs: [build]
    uses: ./.github/workflows/native-image.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:  
      gh-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: [assemble, build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      discussions: write
      issues: write
      pull-requests: write
    outputs:
      HASHES: ${{ steps.attestation-data.outputs.HASHES }}
      TAGNAME: ${{ steps.attestation-data.outputs.TAGNAME }}
    steps:
      - name: Check out source code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
      
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: arconia-*
          path: artifacts
          merge-multiple: true
      
      - name: Inspect artifacts
        run: |
          echo "Artifacts:"
          ls -R artifacts
      
      - name: Release
        uses: jreleaser/release-action@80ffb38fa759704eed4db5c7fcaae3ac1079473e # v2
        with:
          arguments: full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ needs.build.outputs.version }}
      
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          retention-days: 1
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      
      - name: Identify data for attestation
        shell: bash
        id: attestation-data
        run: |
          echo "HASHES=$(cat out/jreleaser/checksums/checksums_sha256.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
          echo "TAGNAME=$(grep tagName out/jreleaser/output.properties | awk -F'=' '{print $2}')" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [ build, release ]
    name: Generate SLSA Provenance Attestation
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    permissions:
      actions: read
      contents: write
      id-token: write
    with:
      base64-subjects: ${{ needs.release.outputs.HASHES }}
      upload-assets: true
      upload-tag-name: ${{ needs.release.outputs.TAGNAME }}
      provenance-name: arconia-cli-${{ needs.build.outputs.version }}.intoto.jsonl
