name: Commit Stage

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.sdkmanrc'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.sdkmanrc'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@6f327093bb6a42fe5eac053d21b168c46aa46f22 # v1.2.4
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      
      - name: Set VERSION environment variable
        id: set_version
        run: |
          VERSION=$(./gradlew properties | grep 'version:' | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Compile and test
        run: ./gradlew build
      
      - name: Native compile and test
        run: ./gradlew nativeBuild

  assemble:
    name: Assemble
    needs: [build]
    uses: ./.github/workflows/native-image.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:  
      gh-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: [assemble, build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      discussions: write
      issues: write
      pull-requests: write
    outputs:
      HASHES: ${{ steps.attestation-data.outputs.HASHES }}
      TAGNAME: ${{ steps.attestation-data.outputs.TAGNAME }}
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: arconia-*
          path: artifacts
          merge-multiple: true
      
      - name: Inspect artifacts
        run: |
          echo "Artifacts:"
          ls -R artifacts
      
      - name: Release
        uses: jreleaser/release-action@80ffb38fa759704eed4db5c7fcaae3ac1079473e # v2
        with:
          arguments: full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ needs.build.outputs.version }}
          JRELEASER_SCOOP_GITHUB_TOKEN: ${{ secrets.JRELEASER_SCOOP_GITHUB_TOKEN }}
      
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          retention-days: 1
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      
      - name: Identify data for attestation
        shell: bash
        id: attestation-data
        run: |
          echo "HASHES=$(cat out/jreleaser/checksums/checksums_sha256.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
          echo "TAGNAME=$(grep tagName out/jreleaser/output.properties | awk -F'=' '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Trigger documentation update
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: arconia-io/arconia-io.github.io
          event-type: docs-update

  provenance:
    needs: [ build, release ]
    name: Generate SLSA Provenance Attestation
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    permissions:
      actions: read
      contents: write
      id-token: write
    with:
      base64-subjects: ${{ needs.release.outputs.HASHES }}
      upload-assets: true
      upload-tag-name: ${{ needs.release.outputs.TAGNAME }}
      provenance-name: arconia-cli-${{ needs.build.outputs.version }}.intoto.jsonl
