name: Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-24.04
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '22'
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate and submit Dependency Graph
      uses: gradle/actions/dependency-submission@v4
