name: Native Image

on:
  workflow_call:
    secrets:
      gh-token:
        description: "Token to interact with the GitHub API without rate limits."
        required: true
    inputs:
      version:
        description: "The project version."
        required: true
        type: string

jobs:
  build-native:
    name: Build Native Image
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux-amd64
          - os: macos-13
            platform: macos-amd64
          - os: macos-latest
            platform: macos-aarch64
          - os: windows-latest
            platform: windows-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@22cc13fe88ef133134b3798e128fb208df55e1f5 # v1.2.3
        with:
          java-version: '23'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.gh-token }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

      - name: Build with Gradle
        run: ./gradlew nativeCompile
      
      - name: Assemble distribution
        run: ./gradlew distZip -ParchiveName="arconia-cli-${{ inputs.version }}-${{ matrix.platform }}.zip"
      
      - name: Verify artifact (Unix)
        if: ${{ matrix.platform != 'windows-amd64' }}
        run: build/native/nativeCompile/arconia help
      
      - name: Verify artifact (Windows)
        if: ${{ matrix.platform == 'windows-amd64' }}
        run: build/native/nativeCompile/arconia.exe help

      - name: Upload artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          retention-days: 1
          name: arconia-cli-${{ inputs.version }}-${{ matrix.platform }}
          path: build/distributions/arconia-cli-${{ inputs.version }}-${{ matrix.platform }}.zip
