name: Native Image

on:
  workflow_call:
    secrets:
      gh-token:
        description: "Token to interact with the GitHub API without rate limits."
        required: true
    inputs:
      version:
        description: "The project version."
        required: true
        type: string

jobs:
  build-native:
    name: Build Native Image
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux-amd64
          - os: macos-13
            platform: macos-amd64
          - os: macos-latest
            platform: macos-aarch64
          - os: windows-latest
            platform: windows-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.gh-token }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew nativeCompile
      
      - name: Assemble distribution
        run: ./gradlew distZip -ParchiveName="arconia-${{ inputs.version }}-${{ matrix.platform }}.zip"
      
      - name: Verify artifact (Unix)
        if: ${{ matrix.platform != 'windows-amd64' }}
        run: build/native/nativeCompile/arconia help
      
      - name: Verify artifact (Windows)
        if: ${{ matrix.platform == 'windows-amd64' }}
        run: build/native/nativeCompile/arconia.exe help

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: artifacts
          path: build/distributions/arconia-${{ inputs.version }}-${{ matrix.platform }}.zip
