name: Native Image

on:
  workflow_call:
    secrets:
      gh-token:
        description: "Token to interact with the GitHub API without rate limits."
        required: true
    inputs:
      version:
        description: "The project version."
        required: true
        type: string

jobs:
  build-native:
    name: Build Native Image
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15, windows-2025]
        include:
          - os: ubuntu-24.04
            platform: linux-amd64
          - os: ubuntu-24.04-arm
            platform: linux-aarch64
          - os: macos-13
            platform: macos-amd64
          - os: macos-15
            platform: macos-aarch64
          - os: windows-2025
            platform: windows-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@6f327093bb6a42fe5eac053d21b168c46aa46f22 # v1.2.4
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.gh-token }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Build with Gradle
        run: ./gradlew nativeCompile
      
      - name: Assemble distribution
        run: ./gradlew distZip -ParchiveName="arconia-cli-${{ inputs.version }}-${{ matrix.platform }}.zip"
      
      - name: Verify artifact (Unix)
        if: ${{ matrix.platform != 'windows-amd64' }}
        run: build/native/nativeCompile/arconia help
      
      - name: Verify artifact (Windows)
        if: ${{ matrix.platform == 'windows-amd64' }}
        run: build/native/nativeCompile/arconia.exe help

      - name: Upload artifact
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          retention-days: 1
          name: arconia-cli-${{ inputs.version }}-${{ matrix.platform }}
          path: build/distributions/arconia-cli-${{ inputs.version }}-${{ matrix.platform }}.zip
